using System;
using System.Globalization;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace MagicCardMarket.Contracts
{
    //https://www.mkmapi.eu/ws/documentation/API_1.1:Entities:Product
    [Serializable]
    [XmlType("product", AnonymousType = true)]
    [XmlRoot(Namespace = "", ElementName = "product", IsNullable = false)]
    public class Product
    {
        [XmlElement("idProduct", Form = XmlSchemaForm.Unqualified)]
        public int Id { get; set; }

        [XmlElement("idMetaproduct", Form = XmlSchemaForm.Unqualified)]
        public int MetaProductId { get; set; }

        [XmlElement("idGame", Form = XmlSchemaForm.Unqualified)]
        public int GameId { get; set; }

        [XmlElement("countReprints", Form = XmlSchemaForm.Unqualified)]
        public string ReprintsCountAsString { get; set; }

        [XmlIgnore]
        public int ReprintsCount
        {
            get
            {
                if (String.IsNullOrWhiteSpace(ReprintsCountAsString))
                    return 0;
                int result;
                if (!int.TryParse(ReprintsCountAsString, out result))
                    return 0;
                return result;
            }
            set { ReprintsCountAsString = value.ToString(CultureInfo.InvariantCulture); }
        }


        [XmlElement("name", Form = XmlSchemaForm.Unqualified)]
        public ProductName[] Names { get; set; }

        [XmlElement("website", Form = XmlSchemaForm.Unqualified)]
        public string WebSite { get; set; }

        [XmlElement("image", Form = XmlSchemaForm.Unqualified)]
        public string Image { get; set; }

        [XmlElement("category", Form = XmlSchemaForm.Unqualified)]
        public ProductCategory Category { get; set; }

        [XmlElement("priceGuide", Form = XmlSchemaForm.Unqualified)]
        public ProductPriceGuide PriceGuide { get; set; }

        [XmlElement("expansion", Form = XmlSchemaForm.Unqualified)]
        public string Expansion { get; set; }

        [XmlElement("expIcon", Form = XmlSchemaForm.Unqualified)]
        public int ExpansionIcon { get; set; }

        [XmlElement("number", Form = XmlSchemaForm.Unqualified)]
        public string Number { get; set; }

        [XmlElement("rarity", Form = XmlSchemaForm.Unqualified)]
        public string Rarity { get; set; }

        [XmlElement("reprint", Form = XmlSchemaForm.Unqualified)]
        public ProductReprint[] Reprints { get; set; }

        [XmlElement("countArticles", Form = XmlSchemaForm.Unqualified)]
        public int ArticlesCount { get; set; }

        [XmlElement("countFoils", Form = XmlSchemaForm.Unqualified)]
        public int FoilsCount { get; set; }
    }

    ////------------------------------------------------------------------------------
    //// <auto-generated>
    ////     This code was generated by a tool.
    ////     Runtime Version:4.0.30319.42000
    ////
    ////     Changes to this file may cause incorrect behavior and will be lost if
    ////     the code is regenerated.
    //// </auto-generated>
    ////------------------------------------------------------------------------------

    //// 
    //// This source code was auto-generated by xsd, Version=4.6.1055.0.
    //// 


    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    //public partial class product
    //{

    //    private string idProductField;

    //    private string idMetaproductField;

    //    private string idGameField;

    //    private string countReprintsField;

    //    private string websiteField;

    //    private string imageField;

    //    private string expansionField;

    //    private string expIconField;

    //    private string numberField;

    //    private string rarityField;

    //    private productName[] nameField;

    //    private productCategory[] categoryField;

    //    private productPriceGuide[] priceGuideField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string idProduct
    //    {
    //        get
    //        {
    //            return this.idProductField;
    //        }
    //        set
    //        {
    //            this.idProductField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string idMetaproduct
    //    {
    //        get
    //        {
    //            return this.idMetaproductField;
    //        }
    //        set
    //        {
    //            this.idMetaproductField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string idGame
    //    {
    //        get
    //        {
    //            return this.idGameField;
    //        }
    //        set
    //        {
    //            this.idGameField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string countReprints
    //    {
    //        get
    //        {
    //            return this.countReprintsField;
    //        }
    //        set
    //        {
    //            this.countReprintsField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string website
    //    {
    //        get
    //        {
    //            return this.websiteField;
    //        }
    //        set
    //        {
    //            this.websiteField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string image
    //    {
    //        get
    //        {
    //            return this.imageField;
    //        }
    //        set
    //        {
    //            this.imageField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string expansion
    //    {
    //        get
    //        {
    //            return this.expansionField;
    //        }
    //        set
    //        {
    //            this.expansionField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string expIcon
    //    {
    //        get
    //        {
    //            return this.expIconField;
    //        }
    //        set
    //        {
    //            this.expIconField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string number
    //    {
    //        get
    //        {
    //            return this.numberField;
    //        }
    //        set
    //        {
    //            this.numberField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string rarity
    //    {
    //        get
    //        {
    //            return this.rarityField;
    //        }
    //        set
    //        {
    //            this.rarityField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("name", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public productName[] name
    //    {
    //        get
    //        {
    //            return this.nameField;
    //        }
    //        set
    //        {
    //            this.nameField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("category", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public productCategory[] category
    //    {
    //        get
    //        {
    //            return this.categoryField;
    //        }
    //        set
    //        {
    //            this.categoryField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("priceGuide", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public productPriceGuide[] priceGuide
    //    {
    //        get
    //        {
    //            return this.priceGuideField;
    //        }
    //        set
    //        {
    //            this.priceGuideField = value;
    //        }
    //    }
    //}

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //public partial class productName
    //{

    //    private string idLanguageField;

    //    private string languageNameField;

    //    private string productName1Field;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string idLanguage
    //    {
    //        get
    //        {
    //            return this.idLanguageField;
    //        }
    //        set
    //        {
    //            this.idLanguageField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string languageName
    //    {
    //        get
    //        {
    //            return this.languageNameField;
    //        }
    //        set
    //        {
    //            this.languageNameField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("productName", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string productName1
    //    {
    //        get
    //        {
    //            return this.productName1Field;
    //        }
    //        set
    //        {
    //            this.productName1Field = value;
    //        }
    //    }
    //}

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //public partial class productCategory
    //{

    //    private string idCategoryField;

    //    private string categoryNameField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string idCategory
    //    {
    //        get
    //        {
    //            return this.idCategoryField;
    //        }
    //        set
    //        {
    //            this.idCategoryField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string categoryName
    //    {
    //        get
    //        {
    //            return this.categoryNameField;
    //        }
    //        set
    //        {
    //            this.categoryNameField = value;
    //        }
    //    }
    //}

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //public partial class productPriceGuide
    //{

    //    private string sELLField;

    //    private string lOWField;

    //    private string lOWEXField;

    //    private string lOWFOILField;

    //    private string aVGField;

    //    private string tRENDField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string SELL
    //    {
    //        get
    //        {
    //            return this.sELLField;
    //        }
    //        set
    //        {
    //            this.sELLField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string LOW
    //    {
    //        get
    //        {
    //            return this.lOWField;
    //        }
    //        set
    //        {
    //            this.lOWField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string LOWEX
    //    {
    //        get
    //        {
    //            return this.lOWEXField;
    //        }
    //        set
    //        {
    //            this.lOWEXField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string LOWFOIL
    //    {
    //        get
    //        {
    //            return this.lOWFOILField;
    //        }
    //        set
    //        {
    //            this.lOWFOILField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string AVG
    //    {
    //        get
    //        {
    //            return this.aVGField;
    //        }
    //        set
    //        {
    //            this.aVGField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    //    public string TREND
    //    {
    //        get
    //        {
    //            return this.tRENDField;
    //        }
    //        set
    //        {
    //            this.tRENDField = value;
    //        }
    //    }
    //}

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    //public partial class NewDataSet
    //{

    //    private product[] itemsField;

    //    /// <remarks/>
    //    [System.Xml.Serialization.XmlElementAttribute("product")]
    //    public product[] Items
    //    {
    //        get
    //        {
    //            return this.itemsField;
    //        }
    //        set
    //        {
    //            this.itemsField = value;
    //        }
    //    }
    //}

    //<product>
    //  <idProduct>5514</idProduct>
    //  <idMetaproduct>2923</idMetaproduct>
    //  <idGame>1</idGame>
    //  <countReprints>457</countReprints>
    //  <name>
    //    <idLanguage>1</idLanguage>
    //    <languageName>English</languageName>
    //    <productName>Island(Version 2)</productName>
    //  </name>
    //  <name>
    //    <idLanguage>2</idLanguage>
    //    <languageName>French</languageName>
    //    <productName>Île(Version 2)</productName>
    //  </name>
    //  <name>
    //    <idLanguage>3</idLanguage>
    //    <languageName>German</languageName>
    //    <productName>Insel(Version 2)</productName>
    //  </name>
    //  <name>
    //    <idLanguage>4</idLanguage>
    //    <languageName>Spanish</languageName>
    //    <productName>Isla(Version 2)</productName>
    //  </name>
    //  <name>
    //    <idLanguage>5</idLanguage>
    //    <languageName>Italian</languageName>
    //    <productName>Isola(Version 2)</productName>
    //  </name>
    //  <website>/Products/Singles/Alpha/Island+%28Version+2%29</website>
    //  <image>./img/cards/Alpha/island2.jpg</image>
    //  <category>
    //    <idCategory>1</idCategory>
    //    <categoryName>Magic Single</categoryName>
    //  </category>
    //  <priceGuide>
    //    <SELL>0</SELL>
    //    <LOW>5</LOW>
    //    <LOWEX>7.5</LOWEX>
    //    <LOWFOIL>0</LOWFOIL>
    //    <AVG>20.37</AVG>
    //    <TREND>11.84</TREND>
    //  </priceGuide>
    //  <expansion>Alpha</expansion>
    //  <expIcon>0</expIcon>
    //  <number></number>
    //  <rarity>Land</rarity>
    //</product>
}
